{{- if .Values.kraan.rbac.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kraan
  namespace: {{.Release.Namespace}}
---
# permissions to do leader election.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kraan-leader-election-role
  namespace: {{.Release.Namespace}}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - configmaps/status
  verbs:
  - get
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kraan-leader-election-rolebinding
  namespace: {{.Release.Namespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kraan-leader-election-role
subjects:
- kind: ServiceAccount
  name: kraan
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kraan-manager
rules:
- apiGroups:
  - kraan.io
  resources:
  - addonslayers
  - addonslayers/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kraan-gitops-source
rules:
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - gitrepositories
  - gitrepositories/status
  - helmrepositories
  - helmrepositories/status
  verbs:
  - watch
  - get
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kraan-helm-release
rules:
- apiGroups:
  - helm.toolkit.fluxcd.io
  resources:
  - helmreleases
  - helmreleases/status
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kraan-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kraan-manager
subjects:
- kind: ServiceAccount
  name: kraan
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kraan-gitops-source
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kraan-gitops-source
subjects:
- kind: ServiceAccount
  name: kraan
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kraan-helm-release
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kraan-helm-release
subjects:
- kind: ServiceAccount
  name: kraan
  namespace: {{.Release.Namespace}}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kraan-deployer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kraan
  namespace: {{.Release.Namespace}}
{{- end }}